### ISSUE TITLE
 can't stat 'pki/ca.crt': No such file or directory

### ISSUE THREAD

**Issue by amir734jj** [dockovpn/dockovpn#174]
I did a `docker-compose down` and now I am seeing this error when doing `docker-compose up`. Is there a problem with persistency?

docker-compose.yml

```yml
version: "3.9"

services:
  ovpn:
    image: alekslitvinenk/openvpn:latest
    cap_add:
      - net_admin
    network_mode: "bridge"
    volumes:
      - ./ovpn:/opt/Dockovpn_data
    ports:
      - "1194:1194/udp"
      - "8080:8080/tcp"
    restart: unless-stopped
```

```
ovpn_1       | Sun Oct 16 17:42:53 2022 Creating tun/tap device.
samba_1      | usermod: no changes
ovpn_1       | cp: can't stat 'pki/ca.crt': No such file or directory
ovpn_1       | cp: can't stat 'pki/issued/MyReq.crt': No such file or directory
ovpn_1       | cp: can't stat 'pki/private/MyReq.key': No such file or directory
ovpn_1       | cp: can't stat 'pki/crl.pem': No such file or directory
ovpn_1       | 2022-10-16 17:42:53 Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).
ovpn_1       | 2022-10-16 17:42:53 WARNING: --topology net30 support for server configs with IPv4 pools will be removed in a future release. Please migrate to --topology subnet as soon as possible.
ovpn_1       | Options error: --ca fails with '/etc/openvpn/ca.crt': No such file or directory (errno=2)
ovpn_1       | Options error: --cert fails with '/etc/openvpn/MyReq.crt': No such file or directory (errno=2)
ovpn_1       | 2022-10-16 17:42:53 WARNING: cannot stat file '/etc/openvpn/MyReq.key': No such file or directory (errno=2)
ovpn_1       | Options error: --key fails with '/etc/openvpn/MyReq.key': No such file or directory (errno=2)
ovpn_1       | Options error: --crl-verify fails with '/etc/openvpn/crl.pem': No such file or directory (errno=2)
ovpn_1       | Options error: Please correct these errors.
ovpn_1       | Use --help for more information.
```
